/* autogenerated by Processing revision 1293 on 2024-12-11 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class digitalRain extends PApplet {

int numDrops = 1000;
float speed = 2;
float[][] drops;
int[] dropValues;
float spacing = 10; // 设置数字之间的间隔

public void setup() {
  /* size commented out by preprocessor */;
  background(0);
  /* smooth commented out by preprocessor */;
  
  drops = new float[numDrops][2];
  dropValues = new int[numDrops];
  
  for (int i = 0; i < numDrops; i++) {
    drops[i][0] = random(width);
    drops[i][1] = random(-height, height);
    dropValues[i] = PApplet.parseInt(random(2));
  }
}

public void draw() {
  background(0);
  fill(0, 255, 0);
  textSize(12);
  
  for (int i = 0; i < numDrops; i++) {
    drops[i][1] += speed;
    
    if (drops[i][1] > height) {
      drops[i][0] = random(width);
      drops[i][1] = random(-20, 0);
    }
    
    float alpha = map(drops[i][1], height/2, height, 255, 0);
    fill(0, 255, 0, alpha);
    
    // 将绘制位置向下偏移spacing像素，避免重叠
    text(dropValues[i], drops[i][0], drops[i][1] + spacing * (i % 10)); 
  }
}


  public void settings() { size(800, 600);
smooth(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "--full-screen", "--bgcolor=#666666", "--stop-color=#cccccc", "digitalRain" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
